# Generated by Django 3.1.7 on 2021-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('process', models.TextField()),
                ('images', models.ImageField(upload_to='media/')),
                ('created_by', models.CharField(max_length=200)),
            ],
        ),
    ]
